"""Regenerate knowledge/index.md from article frontmatter (PR C).

The index is a pure projection now: sectioned by project → subsystem, one table per
subsystem, each row's text coming from that article's `summary:` field. Deterministic,
idempotent, no LLM. Call build() after a compile (compile.py does) or run standalone.

To change the catalog, edit an article's `summary:`/`subsystem:` and rebuild — never
hand-edit index.md.

Usage:  uv run python scripts/build_index.py [--check]
        --check exits non-zero if the on-disk index differs from a fresh build.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
KNOWLEDGE = ROOT / "knowledge"
INDEX = KNOWLEDGE / "index.md"

# Display order; anything unlisted sorts alphabetically after the known ones.
PROJECT_ORDER: list[str] = []  # populated from article frontmatter; no hardcoded slugs
SUBSYSTEM_ORDER = [
    "architecture", "enrichment", "tax-config", "invoicing", "credit-notes",
    "metadata-schema", "emission-cutover", "audit", "sync-cache", "dashboard",
    "owner-statements", "tooling",
]
TYPE_ORDER = {"moc": 0, "concept": 1, "connection": 2, "reference": 3, "qa": 4}

_SCALAR = lambda fm, key: (
    (m := re.search(rf"^{key}:\s*(.+)$", fm, re.M)) and m.group(1).strip()
) or ""


def _read_frontmatter(text: str) -> str:
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            return text[3:end]
    return ""


def _unquote(s: str) -> str:
    s = s.strip()
    if len(s) >= 2 and s[0] == s[-1] and s[0] in "\"'":
        return s[1:-1]
    return s


def collect() -> list[dict]:
    """One record per article: {path, project, subsystem, type, status, summary, updated}."""
    out = []
    for sub in ("mocs", "concepts", "connections", "qa"):
        d = KNOWLEDGE / sub
        if not d.exists():
            continue
        for art in sorted(d.glob("*.md")):
            fm = _read_frontmatter(art.read_text(encoding="utf-8", errors="ignore"))
            if not fm:
                continue
            out.append({
                "link": f"{sub}/{art.stem}",
                "project": _SCALAR(fm, "project") or "(unfiled)",
                "subsystem": _SCALAR(fm, "subsystem") or "(unfiled)",
                "type": _SCALAR(fm, "type") or sub.rstrip("s"),
                "status": _SCALAR(fm, "status") or "active",
                "summary": _unquote(_SCALAR(fm, "summary")),
                "updated": (_SCALAR(fm, "updated") or "")[:10],
            })
    return out


def _ordered(values: set[str], order: list[str]) -> list[str]:
    known = [v for v in order if v in values]
    rest = sorted(v for v in values if v not in order)
    return known + rest


def render(records: list[dict]) -> str:
    by_proj: dict[str, dict[str, list[dict]]] = {}
    for r in records:
        by_proj.setdefault(r["project"], {}).setdefault(r["subsystem"], []).append(r)

    n_proj = len(by_proj)
    lines = [
        "# Knowledge Base Index",
        "",
        f"> Generated by `scripts/build_index.py` from article frontmatter — do not hand-edit.",
        f"> Sectioned by project → subsystem; each row's text is that article's `summary:`.",
        f"> {len(records)} article(s) across {n_proj} project(s). To change a row, edit the",
        f"> article's `summary:` / `subsystem:` and rebuild (the compiler does this automatically).",
        "",
    ]
    for project in _ordered(set(by_proj), PROJECT_ORDER):
        subs = by_proj[project]
        lines.append(f"## {project}")
        lines.append("")
        for subsystem in _ordered(set(subs), SUBSYSTEM_ORDER):
            rows = sorted(subs[subsystem],
                          key=lambda r: (TYPE_ORDER.get(r["type"], 9), r["link"]))
            lines.append(f"### {subsystem}")
            lines.append("")
            lines.append("| Article | Type | Status | Summary | Updated |")
            lines.append("|---------|------|--------|---------|---------|")
            for r in rows:
                summary = r["summary"].replace("|", "\\|") or "—"
                lines.append(
                    f"| [[{r['link']}]] | {r['type']} | {r['status']} | {summary} | {r['updated']} |"
                )
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build() -> int:
    """Regenerate index.md from frontmatter. Returns the article count written."""
    records = collect()
    INDEX.write_text(render(records), encoding="utf-8")
    return len(records)


def main() -> None:
    if "--check" in sys.argv:
        fresh = render(collect())
        current = INDEX.read_text(encoding="utf-8") if INDEX.exists() else ""
        if fresh.strip() != current.strip():
            print("index.md is STALE — run scripts/build_index.py to regenerate.")
            sys.exit(1)
        print("index.md is up to date.")
        return
    n = build()
    print(f"Wrote {INDEX.relative_to(ROOT)} — {n} article(s).")


if __name__ == "__main__":
    main()
